name: Test Workflow

on:
  push:
    branches:
      - main
      
permissions:
  id-token: write 
  contents: read  # This is required for actions/checkout

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Install pytest
        run: pip install pytest
      
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t data_upload_app_v1.0 .
          echo ::set-output name=DOCKER_IMAGE::data_upload_app_v1.0
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: access_token
          # create_credentials_file: 'true'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s
      
      - name: Determine Docker tag
        id: tag
        run: echo ::set-output name=DOCKER_TAG::${{ github.sha }}      
      

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-image-repository/${{ env.DOCKER_IMAGE }}:${{ steps.tag.outputs.DOCKER_TAG }}
            us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-image-repository/${{ env.DOCKER_IMAGE }}:latest
      
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          DOCKER_IMAGE: ${{ steps.build-image.outputs.DOCKER_IMAGE }}
          REPO_NAME: us-central1/docker-image-repository

     
     
     
      # - name: Tag Docker image
      #   run: docker tag data_upload gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ steps.tag.outputs.DOCKER_TAG }}
        
      # - name: Push Docker image to Google Artifact Registry
      #   run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ steps.tag.outputs.DOCKER_TAG }}


      
        # - name: Tag Docker image
      #   run: docker tag data_upload gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}:${{ steps.tag.outputs.DOCKER_TAG }}
        

      
      # - name: Push Docker image to Google Artifact Registry
      #   run: docker push gcr.io/${{ secrets.PROJECT_ID }}/data_upload_app_v1.0:${{ github.sha }}

      # - name: Run tests
      #   run: pytest tests/
   