name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Install pytest
        run: pip install pytest
      
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t data_upload_app_v1.0 .
      
      - name: Tag Docker image
        run: docker tag data_upload eu.gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ steps.tag.outputs.DOCKER_TAG }}

      - name: Push Docker image to Google Artifact Registry
        run: docker push eu.gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ steps.tag.outputs.DOCKER_TAG }}
       
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REPO_NAME: docker-image-repository
          #TAG: latest 
      
      
      # - name: Run tests
      #   run: pytest tests/
   